language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.5
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: 'action_default_fallback'
  enable_fallback_prediction: true

# Accessibility Configuration
assistant_config:
  name: 'Pain Tracker'
  voice:
    enabled: true
    rate: 'medium' # Can be adjusted with speak_slower intent
    volume: 'medium' # Can be adjusted with speak_louder intent
    pitch: 'medium'
    voice_id: 'en-US-Neural2-F' # Use a clear, natural-sounding voice

  text:
    font_size: 'large' # Default to larger font for readability
    high_contrast: true
    simple_language: false # Can be enabled with simplify_question intent

  input_methods:
    voice: true
    text: true
    buttons: true # Important for users with motor impairments
    touch: true

  response_timing:
    delay_between_messages: 1000 # ms, gives users time to process information

  ui:
    show_typing_indicator: true
    button_size: 'large'
    color_blind_friendly: true
    dark_mode: false # Can be toggled by user

  help:
    context_sensitive: true
    always_available: true
    simplified_instructions: true

  speech_recognition:
    enabled: true
    adaptive: true # Adapts to speech patterns, helpful for users with speech impairments
    timeout: 10000 # Longer timeout for users who may need more time

# Custom settings for different impairments
impairment_adaptations:
  tremor:
    button_size: 'extra_large'
    button_spacing: 'wide'
    dwell_time: 500 # ms, prevents accidental clicks
    input_debounce: 300 # ms, prevents multiple inputs from tremors

  visual:
    font_size: 'extra_large'
    high_contrast: true
    screen_reader_optimized: true
    descriptions_for_images: true

  cognitive:
    simple_language: true
    step_by_step_instructions: true
    fewer_options: true
    reminder_prompts: true
    patient_timeout: 30000 # ms, extra time before timing out
assistant_id: 20250326-054249-dynamic-mallet
